import matplotlib.pyplot as plt
from funnel_analysis import app_data, funnel_count_os, funnel_count_age, funnel_count_gender, avg_app_usage, conversion_rate_os

colors = ['#8dd3c7','#ffffb3','#9575cd','#fb8072']
funnel_count_os.plot(kind='bar', figsize=(10,5), color=colors)
plt.title('User Retention By Operating System', fontsize=14, fontweight='bold')
plt.xlabel('Operating System', fontsize=12)
plt.ylabel('Number of Users', fontsize=12)
plt.xticks(rotation=0)
plt.legend(title='Conversion Stage', fontsize=10, title_fontsize=11, loc='upper right', bbox_to_anchor=(1.5, 1))
plt.tight_layout()
plt.savefig('User Retention Based On Operating System.')
plt.show()
plt.close()

funnel_count_age.plot(kind='bar', figsize=(55,20), color = colors)
plt.title('User Retention By Age', fontsize=32, fontweight='bold')
plt.ylabel('Number of Users')
plt.xlabel('Age')
plt.xticks(rotation=45)
plt.legend(title='Conversion Stage', fontsize= 18, loc='upper right', bbox_to_anchor=(1.09, 2))
plt.savefig('User Retention Based on Age.')
plt.show()
plt.close()

funnel_count_gender.plot(kind='bar', figsize=(12,5), color = colors)
plt.title('User Retention by Gender', fontsize=18, fontweight='bold')
plt.ylabel('Number of Users')
plt.xlabel('Gender')
plt.xticks(rotation=0)
plt.legend(title='Conversion Stage', loc='upper right', bbox_to_anchor=(1.14, 1))
plt.savefig('User Retention Based On Gender.png')
plt.show()
plt.close()

avg_app_usage.plot(kind='bar', color='#fb8072', figsize=(7,7))
plt.title('Average App Usage Time Based on User Retention Stages', fontsize=14, fontweight='bold')
plt.ylabel('Minutes')
plt.xlabel('Conversion Stage')
plt.tight_layout()
plt.savefig('Average App Usage  Time by User Retention Stages')
plt.show()
plt.close()

conversion_rate_os[['Download_to_Activation_%','Activation_to_Trial_%','Trial_to_Paid_%']].plot(kind='bar', figsize=(13,5), color = ('#8dd3c7','#ffffb3','#fb8072'))
plt.title('User Retention Stages Conversion Rates Based on Operating System', fontsize=14, fontweight='bold')
plt.ylabel('Conversion Rate (%)')
plt.xlabel('Operating System')
plt.xticks(rotation=0)
plt.legend(title='Conversion', fontsize=7, loc='upper right', bbox_to_anchor=(1.13,1))
plt.tight_layout()
plt.savefig('Conversion Rates (%)')
plt.show()
plt.close()